"""Curated Watchlist of 52+ Top Egyptian University Student Activities, IEEE, Enactus, TEDx, GDG, and Career Centers.

Used by MetaPlaywrightScraper and the Social Media Intelligence Hub to poll high-yield
Egyptian campus pages directly every 12 hours, capturing events even when captions omit generic keywords.
"""

from typing import Any, Dict, List, Optional

EGYPT_CAMPUS_WATCHLIST: List[Dict[str, Any]] = [
    # --- CAIRO & GIZA PUBLIC UNIVERSITIES (CU, ASU, Helwan) ---
    {
        "id": "wl_ieee_cusb",
        "name": "IEEE Cairo University Student Branch (IEEE CUSB)",
        "category": "IEEE & Engineering",
        "university": "Cairo University",
        "city": "Giza",
        "facebook_url": "https://www.facebook.com/IEEECUSB/events",
        "instagram_handle": "ieeecusb",
        "b2c_priority_score": 96,
        "typical_events": "Egyptian Engineering Day, Tech Summits, AI Bootcamps",
    },
    {
        "id": "wl_ieee_asusb",
        "name": "IEEE Ain Shams University Student Branch (IEEE ASUSB)",
        "category": "IEEE & Engineering",
        "university": "Ain Shams University",
        "city": "Cairo",
        "facebook_url": "https://www.facebook.com/IEEE.ASUSB/events",
        "instagram_handle": "ieeeasusb",
        "b2c_priority_score": 95,
        "typical_events": "Career Fairs, Robotics Challenges, Technical Workshops",
    },
    {
        "id": "wl_scci_cu",
        "name": "SCCI Cairo University (Student Conference for Communication & Information)",
        "category": "Student Activity",
        "university": "Cairo University",
        "city": "Giza",
        "facebook_url": "https://www.facebook.com/SCCICU/events",
        "instagram_handle": "sccicu",
        "b2c_priority_score": 95,
        "typical_events": "Annual Student Tech & Business Conference, Opening Ceremonies",
    },
    {
        "id": "wl_stp_cu",
        "name": "STP Cairo University (Steps Towards Progress)",
        "category": "Student Activity",
        "university": "Cairo University",
        "city": "Giza",
        "facebook_url": "https://www.facebook.com/STP.Organization/events",
        "instagram_handle": "stp_egypt",
        "b2c_priority_score": 93,
        "typical_events": "Youth Development Conferences, Engineering & Career Tracks",
    },
    {
        "id": "wl_enactus_cu",
        "name": "Enactus Cairo University",
        "category": "Enactus & Entrepreneurship",
        "university": "Cairo University",
        "city": "Giza",
        "facebook_url": "https://www.facebook.com/EnactusCairoUniversity/events",
        "instagram_handle": "enactuscairo",
        "b2c_priority_score": 95,
        "typical_events": "Social Entrepreneurship Summits, National Competition Prep",
    },
    {
        "id": "wl_enactus_asu",
        "name": "Enactus Ain Shams University",
        "category": "Enactus & Entrepreneurship",
        "university": "Ain Shams University",
        "city": "Cairo",
        "facebook_url": "https://www.facebook.com/EnactusASU/events",
        "instagram_handle": "enactusasu",
        "b2c_priority_score": 94,
        "typical_events": "Entrepreneurship Bootcamps, Youth Impact Exhibitions",
    },
    {
        "id": "wl_tedx_cu",
        "name": "TEDxCairoUniversity",
        "category": "TEDx & Youth Summits",
        "university": "Cairo University",
        "city": "Giza",
        "facebook_url": "https://www.facebook.com/TEDxCairoUniversity/events",
        "instagram_handle": "tedxcairouniversity",
        "b2c_priority_score": 96,
        "typical_events": "Annual TEDx Youth Summit, Speaker Salons",
    },
    {
        "id": "wl_tedx_asu",
        "name": "TEDxAinShamsUniversity",
        "category": "TEDx & Youth Summits",
        "university": "Ain Shams University",
        "city": "Cairo",
        "facebook_url": "https://www.facebook.com/TEDxAinShamsUniversity/events",
        "instagram_handle": "tedxainshamsuniversity",
        "b2c_priority_score": 95,
        "typical_events": "TEDx Main Stage Conference, Campus Innovation Talks",
    },
    {
        "id": "wl_asu_career_center",
        "name": "ASU Career Center (Ain Shams University)",
        "category": "Career Center",
        "university": "Ain Shams University",
        "city": "Cairo",
        "facebook_url": "https://www.facebook.com/ASUCareerCenter/events",
        "instagram_handle": "asucareercenter",
        "b2c_priority_score": 98,
        "typical_events": "Annual Employment Fair, Corporate Recruitment Days, Employer Panels",
    },
    {
        "id": "wl_cu_uche",
        "name": "Cairo University Center for Career Development (UCCD)",
        "category": "Career Center",
        "university": "Cairo University",
        "city": "Giza",
        "facebook_url": "https://www.facebook.com/UCCDCairoUniversity/events",
        "instagram_handle": "uccd_cu",
        "b2c_priority_score": 97,
        "typical_events": "Campus Job Fairs, Employability Skills Bootcamps",
    },
    {
        "id": "wl_msp_cu",
        "name": "MSP Tech Club Cairo University",
        "category": "GDG / Tech Club",
        "university": "Cairo University",
        "city": "Giza",
        "facebook_url": "https://www.facebook.com/MSPCU/events",
        "instagram_handle": "msp_cu",
        "b2c_priority_score": 92,
        "typical_events": "AI & Cloud Hackathons, Software Engineering Bootcamps",
    },
    {
        "id": "wl_msp_asu",
        "name": "MSP Tech Club Ain Shams University",
        "category": "GDG / Tech Club",
        "university": "Ain Shams University",
        "city": "Cairo",
        "facebook_url": "https://www.facebook.com/ASUMSP/events",
        "instagram_handle": "msp_asu",
        "b2c_priority_score": 92,
        "typical_events": "Microsoft Developer Days, Campus Tech Summits",
    },
    {
        "id": "wl_gdg_cairo",
        "name": "GDG Cairo (Google Developer Group Cairo)",
        "category": "GDG / Tech Club",
        "university": "Greater Cairo Tech Ecosystem",
        "city": "Cairo",
        "facebook_url": "https://www.facebook.com/GDGCairo/events",
        "instagram_handle": "gdgcairo",
        "b2c_priority_score": 96,
        "typical_events": "DevFest Cairo, Google I/O Extended, Women Techmakers",
    },
    {
        "id": "wl_gdg_new_cairo",
        "name": "GDG New Cairo",
        "category": "GDG / Tech Club",
        "university": "New Cairo Universities",
        "city": "New Cairo",
        "facebook_url": "https://www.facebook.com/GDGNewCairo/events",
        "instagram_handle": "gdgnewcairo",
        "b2c_priority_score": 93,
        "typical_events": "DevFest New Cairo, AI & Android Hackathons",
    },
    {
        "id": "wl_gdg_october",
        "name": "GDG 6th of October",
        "category": "GDG / Tech Club",
        "university": "October & Zewail Universities",
        "city": "Giza",
        "facebook_url": "https://www.facebook.com/GDG6October/events",
        "instagram_handle": "gdg6october",
        "b2c_priority_score": 92,
        "typical_events": "DevFest October, Cloud Study Jams",
    },
    {
        "id": "wl_ieee_hsb",
        "name": "IEEE Helwan Student Branch",
        "category": "IEEE & Engineering",
        "university": "Helwan University",
        "city": "Cairo",
        "facebook_url": "https://www.facebook.com/ieeehsb/events",
        "instagram_handle": "ieeehsb",
        "b2c_priority_score": 90,
        "typical_events": "Helwan Engineering Day, Tech Workshops",
    },
    {
        "id": "wl_enactus_helwan",
        "name": "Enactus Helwan University",
        "category": "Enactus & Entrepreneurship",
        "university": "Helwan University",
        "city": "Cairo",
        "facebook_url": "https://www.facebook.com/EnactusHelwan/events",
        "instagram_handle": "enactushelwan",
        "b2c_priority_score": 89,
        "typical_events": "Youth Entrepreneurship & Sustainability Days",
    },

    # --- PRIVATE & INTERNATIONAL UNIVERSITIES (AUC, GUC, BUE, Nile, Zewail, MIU,MSA) ---
    {
        "id": "wl_auc_su",
        "name": "AUC Student Union (American University in Cairo)",
        "category": "Student Union",
        "university": "The American University in Cairo (AUC)",
        "city": "New Cairo",
        "facebook_url": "https://www.facebook.com/AUCStudentUnion/events",
        "instagram_handle": "auc_su",
        "b2c_priority_score": 97,
        "typical_events": "AUC Employment Fair, Club Carnival, Leadership Conferences",
    },
    {
        "id": "wl_auc_vlab",
        "name": "AUC Venture Lab & Entrepreneurship Club",
        "category": "Innovation Hub",
        "university": "The American University in Cairo (AUC)",
        "city": "New Cairo",
        "facebook_url": "https://www.facebook.com/AUCVentureLab/events",
        "instagram_handle": "aucvlab",
        "b2c_priority_score": 95,
        "typical_events": "Demo Days, Startup Summits, Fintech Accelerators",
    },
    {
        "id": "wl_auc_cimun",
        "name": "CIMUN & MAL AUC (Cairo International Model United Nations)",
        "category": "Student Activity",
        "university": "The American University in Cairo (AUC)",
        "city": "New Cairo",
        "facebook_url": "https://www.facebook.com/CIMUNAUC/events",
        "instagram_handle": "cimun_auc",
        "b2c_priority_score": 93,
        "typical_events": "International Model UN Conferences, Delegate Recruitment",
    },
    {
        "id": "wl_tedx_auc",
        "name": "TEDxAUC",
        "category": "TEDx & Youth Summits",
        "university": "The American University in Cairo (AUC)",
        "city": "New Cairo",
        "facebook_url": "https://www.facebook.com/TEDxAUC/events",
        "instagram_handle": "tedxauc",
        "b2c_priority_score": 95,
        "typical_events": "Annual TEDxAUC Conference, Youth Thought Leadership",
    },
    {
        "id": "wl_guc_mun",
        "name": "GUCMUN & Bdaya GUC (German University in Cairo)",
        "category": "Student Activity",
        "university": "German University in Cairo (GUC)",
        "city": "New Cairo",
        "facebook_url": "https://www.facebook.com/GUCMUN/events",
        "instagram_handle": "gucmun",
        "b2c_priority_score": 95,
        "typical_events": "GUC Model UN, Campus Career & Leadership Summits",
    },
    {
        "id": "wl_ieee_guc",
        "name": "IEEE GUC Student Branch",
        "category": "IEEE & Engineering",
        "university": "German University in Cairo (GUC)",
        "city": "New Cairo",
        "facebook_url": "https://www.facebook.com/IEEEGUC/events",
        "instagram_handle": "ieeeguc",
        "b2c_priority_score": 94,
        "typical_events": "Robotics & Embedded Systems Hackathons, Engineering Summits",
    },
    {
        "id": "wl_tedx_guc",
        "name": "TEDxGUC",
        "category": "TEDx & Youth Summits",
        "university": "German University in Cairo (GUC)",
        "city": "New Cairo",
        "facebook_url": "https://www.facebook.com/TEDxGUC/events",
        "instagram_handle": "tedxguc",
        "b2c_priority_score": 94,
        "typical_events": "TEDxGUC Main Conference, Campus Innovation Talks",
    },
    {
        "id": "wl_bue_su",
        "name": "BUE Student Union (British University in Egypt)",
        "category": "Student Union",
        "university": "British University in Egypt (BUE)",
        "city": "New Cairo",
        "facebook_url": "https://www.facebook.com/BUESU/events",
        "instagram_handle": "buestudentunion",
        "b2c_priority_score": 94,
        "typical_events": "BUE Career Fair, Orientation Festival, Model COP",
    },
    {
        "id": "wl_ieee_bue",
        "name": "IEEE BUE Student Branch",
        "category": "IEEE & Engineering",
        "university": "British University in Egypt (BUE)",
        "city": "New Cairo",
        "facebook_url": "https://www.facebook.com/IEEEBUESB/events",
        "instagram_handle": "ieeebuesb",
        "b2c_priority_score": 91,
        "typical_events": "Engineering & AI Summits, Campus Tech Days",
    },
    {
        "id": "wl_nile_su",
        "name": "Nile University Student Union & NilePreneurs",
        "category": "Innovation Hub",
        "university": "Nile University",
        "city": "Giza",
        "facebook_url": "https://www.facebook.com/NilePreneurs/events",
        "instagram_handle": "nilepreneurs",
        "b2c_priority_score": 95,
        "typical_events": "Startup Hackathons, Nile University Career Fair, Incubation Demo Days",
    },
    {
        "id": "wl_zewail_sf",
        "name": "Zewail City Science Festival & Student Union",
        "category": "Student Union",
        "university": "Zewail City of Science and Technology",
        "city": "Giza",
        "facebook_url": "https://www.facebook.com/ZewailCityScienceFestival/events",
        "instagram_handle": "zcsf_egypt",
        "b2c_priority_score": 96,
        "typical_events": "Annual Zewail City Science Festival, Youth STEM Summits",
    },
    {
        "id": "wl_ieee_zewail",
        "name": "IEEE Zewail City Student Branch",
        "category": "IEEE & Engineering",
        "university": "Zewail City of Science and Technology",
        "city": "Giza",
        "facebook_url": "https://www.facebook.com/IEEEZCSB/events",
        "instagram_handle": "ieeezcsb",
        "b2c_priority_score": 93,
        "typical_events": "AI & Quantum Computing Workshops, STEM Hackathons",
    },
    {
        "id": "wl_miu_mun",
        "name": "MIU Student Activities & ASCC (Misr International University)",
        "category": "Student Activity",
        "university": "Misr International University (MIU)",
        "city": "Cairo",
        "facebook_url": "https://www.facebook.com/ASCCMIU/events",
        "instagram_handle": "ascc_miu",
        "b2c_priority_score": 90,
        "typical_events": "MIU Career Day, Business & Tech Simulation Conferences",
    },
    {
        "id": "wl_msa_career",
        "name": "MSA University Career Placement Center",
        "category": "Career Center",
        "university": "MSA University",
        "city": "Giza",
        "facebook_url": "https://www.facebook.com/MSAUniversityOfficial/events",
        "instagram_handle": "msauniversity",
        "b2c_priority_score": 91,
        "typical_events": "MSA Annual Job Fair, Graduation Project Expo",
    },

    # --- ALEXANDRIA HUB (Alexandria Univ, AASTMT, E-JUST, Bibliotheca) ---
    {
        "id": "wl_ieee_alexsb",
        "name": "IEEE Alexandria Student Branch (IEEE AlexSB)",
        "category": "IEEE & Engineering",
        "university": "Alexandria University",
        "city": "Alexandria",
        "facebook_url": "https://www.facebook.com/IEEEAlexSB/events",
        "instagram_handle": "ieeealexsb",
        "b2c_priority_score": 96,
        "typical_events": "Alexandria Engineering Forum, Software & AI Bootcamps",
    },
    {
        "id": "wl_enactus_alex",
        "name": "Enactus Alexandria University",
        "category": "Enactus & Entrepreneurship",
        "university": "Alexandria University",
        "city": "Alexandria",
        "facebook_url": "https://www.facebook.com/EnactusAlexandriaUniversity/events",
        "instagram_handle": "enactusalexu",
        "b2c_priority_score": 94,
        "typical_events": "Social Innovation Summits, Youth Leadership Days",
    },
    {
        "id": "wl_gdg_alex",
        "name": "GDG Alexandria (Google Developer Group Alexandria)",
        "category": "GDG / Tech Club",
        "university": "Alexandria Tech Ecosystem",
        "city": "Alexandria",
        "facebook_url": "https://www.facebook.com/GDGAlexandria/events",
        "instagram_handle": "gdgalexandria",
        "b2c_priority_score": 95,
        "typical_events": "DevFest Alexandria, I/O Extended Alexandria, Women Techmakers",
    },
    {
        "id": "wl_tedx_alexu",
        "name": "TEDxAlexandriaUniversity",
        "category": "TEDx & Youth Summits",
        "university": "Alexandria University",
        "city": "Alexandria",
        "facebook_url": "https://www.facebook.com/TEDxAlexandriaUniversity/events",
        "instagram_handle": "tedxalexu",
        "b2c_priority_score": 93,
        "typical_events": "Annual TEDx Youth Summit Alexandria",
    },
    {
        "id": "wl_aast_ec",
        "name": "AAST Entrepreneurship Center & Rally Egypt",
        "category": "Innovation Hub",
        "university": "Arab Academy for Science, Technology & Maritime Transport (AASTMT)",
        "city": "Alexandria",
        "facebook_url": "https://www.facebook.com/AASTEC/events",
        "instagram_handle": "aastec",
        "b2c_priority_score": 96,
        "typical_events": "AASTMT Startup Rally, Maritime & Tech Innovation Summits",
    },
    {
        "id": "wl_ejust_clubs",
        "name": "E-JUST Student Activities & Career Fair (Borg El Arab)",
        "category": "Career Center",
        "university": "Egypt-Japan University of Science and Technology (E-JUST)",
        "city": "Alexandria",
        "facebook_url": "https://www.facebook.com/EJUST.Official/events",
        "instagram_handle": "ejust_official",
        "b2c_priority_score": 93,
        "typical_events": "E-JUST Employment Fair, Japan-Egypt Science Symposiums",
    },
    {
        "id": "wl_bib_alex",
        "name": "Bibliotheca Alexandrina Youth & Science Programs",
        "category": "Innovation Hub",
        "university": "Bibliotheca Alexandrina",
        "city": "Alexandria",
        "facebook_url": "https://www.facebook.com/bibalexOfficial/events",
        "instagram_handle": "bibliotheca_alexandrina",
        "b2c_priority_score": 94,
        "typical_events": "Youth Forums, Tech & Book Fairs, International Conferences",
    },

    # --- DELTA HUB (Tanta, Mansoura, Zagazig, Menoufia) ---
    {
        "id": "wl_ieee_tanta",
        "name": "IEEE Tanta Student Branch (Sebor Campus)",
        "category": "IEEE & Engineering",
        "university": "Tanta University",
        "city": "Tanta",
        "facebook_url": "https://www.facebook.com/IEEETantaSB/events",
        "instagram_handle": "ieeetantasb",
        "b2c_priority_score": 95,
        "typical_events": "Delta Tech Summit, Engineering & AI Workshops at Sebor Campus",
    },
    {
        "id": "wl_enactus_tanta",
        "name": "Enactus Tanta University",
        "category": "Enactus & Entrepreneurship",
        "university": "Tanta University",
        "city": "Tanta",
        "facebook_url": "https://www.facebook.com/EnactusTanta/events",
        "instagram_handle": "enactustanta",
        "b2c_priority_score": 93,
        "typical_events": "Delta Youth Entrepreneurship Forum, Campus Recruitment",
    },
    {
        "id": "wl_gdg_damanhour_delta",
        "name": "GDG Delta & Tanta Tech Community",
        "category": "GDG / Tech Club",
        "university": "Tanta & Delta Universities",
        "city": "Tanta",
        "facebook_url": "https://www.facebook.com/GDGDelta/events",
        "instagram_handle": "gdgdelta",
        "b2c_priority_score": 92,
        "typical_events": "DevFest Delta, Flutter & AI Hackathons",
    },
    {
        "id": "wl_tanta_uccd",
        "name": "Tanta University Career Development Center (UCCD)",
        "category": "Career Center",
        "university": "Tanta University",
        "city": "Tanta",
        "facebook_url": "https://www.facebook.com/UCCDTanta/events",
        "instagram_handle": "uccd_tanta",
        "b2c_priority_score": 96,
        "typical_events": "Tanta University Annual Job Fair, Sebor Campus Career Days",
    },
    {
        "id": "wl_cat_reloaded_mansoura",
        "name": "CAT Reloaded (Mansoura University Computer Science & Eng)",
        "category": "GDG / Tech Club",
        "university": "Mansoura University",
        "city": "Mansoura",
        "facebook_url": "https://www.facebook.com/CATReloaded/events",
        "instagram_handle": "catreloaded",
        "b2c_priority_score": 96,
        "typical_events": "Scope Conference Mansoura, Open Source & AI Bootcamps",
    },
    {
        "id": "wl_ieee_mansoura",
        "name": "IEEE Mansoura Student Branch",
        "category": "IEEE & Engineering",
        "university": "Mansoura University",
        "city": "Mansoura",
        "facebook_url": "https://www.facebook.com/IEEEMansSB/events",
        "instagram_handle": "ieeemanssb",
        "b2c_priority_score": 94,
        "typical_events": "Mansoura Engineering & Robotics Forum, Tech Career Fair",
    },
    {
        "id": "wl_mega_mansoura",
        "name": "MEGA Team Mansoura University",
        "category": "Student Activity",
        "university": "Mansoura University",
        "city": "Mansoura",
        "facebook_url": "https://www.facebook.com/MEGATeam.mu/events",
        "instagram_handle": "megateam_mu",
        "b2c_priority_score": 92,
        "typical_events": "Software & Business Youth Tracks, Campus Summits",
    },
    {
        "id": "wl_ieee_zsb",
        "name": "IEEE Zagazig Student Branch (IEEE ZSB)",
        "category": "IEEE & Engineering",
        "university": "Zagazig University",
        "city": "Sharkia",
        "facebook_url": "https://www.facebook.com/IEEEZSB/events",
        "instagram_handle": "ieeezsb",
        "b2c_priority_score": 92,
        "typical_events": "Zagazig Engineering Day, Sharkia Youth Tech Conference",
    },

    # --- UPPER EGYPT & CANAL HUBS + NATIONAL INNOVATION HUBS ---
    {
        "id": "wl_ieee_assiut",
        "name": "IEEE Assiut Student Branch",
        "category": "IEEE & Engineering",
        "university": "Assiut University",
        "city": "Assiut",
        "facebook_url": "https://www.facebook.com/IEEEAssiutSB/events",
        "instagram_handle": "ieeeassiutsb",
        "b2c_priority_score": 93,
        "typical_events": "Upper Egypt Tech Summit, Robotics & Embedded Hackathons",
    },
    {
        "id": "wl_enactus_assiut",
        "name": "Enactus Assiut University",
        "category": "Enactus & Entrepreneurship",
        "university": "Assiut University",
        "city": "Assiut",
        "facebook_url": "https://www.facebook.com/EnactusAssiut/events",
        "instagram_handle": "enactusassiut",
        "b2c_priority_score": 91,
        "typical_events": "Upper Egypt Entrepreneurship & Youth Leadership Days",
    },
    {
        "id": "wl_creativa_hubs",
        "name": "Creativa Innovation Hubs Egypt (ITIDA / TIEC Nationwide)",
        "category": "Innovation Hub",
        "university": "All Egyptian Universities (18+ Governorates)",
        "city": "Cairo",
        "facebook_url": "https://www.facebook.com/CreativaHubsEgypt/events",
        "instagram_handle": "creativahubsegypt",
        "b2c_priority_score": 98,
        "typical_events": "Nationwide University Hackathons, Freelancing & Startup Bootcamps",
    },
    {
        "id": "wl_greek_campus",
        "name": "The Greek Campus (Downtown Cairo Technology & Innovation Park)",
        "category": "Innovation Hub",
        "university": "Downtown Cairo Startup & Youth Hub",
        "city": "Cairo",
        "facebook_url": "https://www.facebook.com/TheGreekCampus/events",
        "instagram_handle": "thegreekcampus",
        "b2c_priority_score": 98,
        "typical_events": "RiseUp Summit, Career Fairs, Youth Cultural & Tech Expos",
    },
    {
        "id": "wl_hult_prize_egypt",
        "name": "Hult Prize Egypt (National Campus Programs)",
        "category": "Enactus & Entrepreneurship",
        "university": "All Egyptian Universities",
        "city": "Cairo",
        "facebook_url": "https://www.facebook.com/HultPrizeEgypt/events",
        "instagram_handle": "hultprizeegypt",
        "b2c_priority_score": 96,
        "typical_events": "On-Campus Finals, National Social Entrepreneurship Summits",
    },
    {
        "id": "wl_epsf_egypt",
        "name": "EPSF (Egyptian Pharmaceutical Students' Federation)",
        "category": "Student Activity",
        "university": "35+ Pharmacy Faculties Across Egypt",
        "city": "Cairo",
        "facebook_url": "https://www.facebook.com/EPSF.Official/events",
        "instagram_handle": "epsf_egypt",
        "b2c_priority_score": 93,
        "typical_events": "Annual National Congress, Public Health & Career Fairs",
    },
]


def get_campus_watchlist(city: Optional[str] = None, category: Optional[str] = None) -> List[Dict[str, Any]]:
    """Return the 52-page Egyptian Campus Watchlist filtered by optional city or category."""
    results = list(EGYPT_CAMPUS_WATCHLIST)
    if city:
        c_low = city.strip().lower()
        if c_low and c_low != "all":
            results = [
                item for item in results
                if c_low in item["city"].lower() or c_low in item["university"].lower()
            ]
    if category:
        cat_low = category.strip().lower()
        if cat_low and cat_low != "all":
            results = [
                item for item in results
                if cat_low in item["category"].lower()
            ]
    return results


def get_priority_watchlist_queries(city: Optional[str] = None, limit: int = 8) -> List[tuple[str, str]]:
    """Return top priority (label, facebook_url) tuples for MetaPlaywrightScraper polling."""
    items = get_campus_watchlist(city=city)
    items.sort(key=lambda x: x.get("b2c_priority_score", 90), reverse=True)
    return [(item["name"], item["facebook_url"]) for item in items[:limit]]
